// Code generated by godddx, DO AVOID EDIT.
package uniqueid

import (
	"context"

	"github.com/ixugo/goddd/pkg/orm"
)

// UniqueIDStorer Instantiation interface
type UniqueIDStorer interface {
	List(context.Context, *[]*UniqueID, orm.Pager, ...orm.QueryOption) (int64, error)
	Get(context.Context, *UniqueID, ...orm.QueryOption) error
	Create(context.Context, *UniqueID) error
	Update(context.Context, *UniqueID, func(*UniqueID), ...orm.QueryOption) error
	Delete(context.Context, *UniqueID, ...orm.QueryOption) error
}
