// Code generated by godddx, DO AVOID EDIT.
package token

import (
	"github.com/ixugo/goddd/pkg/conc"
)

// Storer data persistence
type Storer interface {
	Token() TokenStorer
}

// Core business domain
type Core struct {
	store Storer
	data  *conc.TTLMap[string, struct{}]
}

// NewCore create business domain
func NewCore(store Storer) Core {
	return Core{store: store, data: conc.NewTTLMap[string, struct{}]()}
}
