// Code generated by godddx, DO AVOID EDIT.
package token

import (
	"context"
	"log/slog"
	"time"

	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/goddd/pkg/reason"
	"github.com/jinzhu/copier"
)

// TokenStorer Instantiation interface
type TokenStorer interface {
	List(context.Context, *[]*Token, orm.Pager, ...orm.QueryOption) (int64, error)
	Get(context.Context, *Token, ...orm.QueryOption) error
	Create(context.Context, *Token) error
	Update(context.Context, *Token, func(*Token), ...orm.QueryOption) error
	Delete(context.Context, *Token, ...orm.QueryOption) error
	DeleteExpired(ctx context.Context, before time.Time) ([]string, error)
	DeleteAllForUser(ctx context.Context, scope, userID string) ([]string, error)
	// 主动过期的函数，记录过期的原因，对用户友好
	Expire(ctx context.Context, scope, userID, reason string) ([]string, error)
}

// FindToken Paginated search
func (c Core) ListTokens(ctx context.Context, in *FindTokenInput) ([]*Token, int64, error) {
	query := orm.NewQuery(1).OrderBy("created_at DESC")

	items := make([]*Token, 0, in.Limit())
	total, err := c.store.Token().List(ctx, &items, in, query.Encode()...)
	if err != nil {
		return nil, 0, reason.ErrDB.Withf(`Find err[%s]`, err.Error())
	}
	return items, total, nil
}

// GetToken Query a single object
func (c Core) GetToken(ctx context.Context, id int) (*Token, error) {
	out := Token{ID: id}
	if err := c.store.Token().Get(ctx, &out); err != nil {
		if orm.IsErrRecordNotFound(err) {
			return nil, reason.ErrNotFound.Withf(`Get err[%s]`, err.Error())
		}
		return nil, reason.ErrDB.Withf(`Get err[%s]`, err.Error())
	}
	return &out, nil
}

// Create Token Insert into database
func (c Core) CreateToken(ctx context.Context, in *AddTokenInput) (*Token, error) {
	var out Token
	if err := copier.Copy(&out, in); err != nil {
		slog.ErrorContext(ctx, "Copy", "err", err)
	}
	out.UpdatedAt = orm.Now()
	if err := c.store.Token().Create(ctx, &out); err != nil {
		return nil, reason.ErrDB.Withf(`Add err[%s]`, err.Error())
	}
	return &out, nil
}

// UpdateToken Update object information
func (c Core) UpdateToken(ctx context.Context, in *EditTokenInput, id int) (*Token, error) {
	var out Token
	if err := c.store.Token().Update(ctx, &out, func(b *Token) {
		if err := copier.Copy(b, in); err != nil {
			slog.ErrorContext(ctx, "Copy", "err", err)
		}
	}, orm.Where("id=?", id)); err != nil {
		return nil, reason.ErrDB.Withf(`Edit err[%s]`, err.Error())
	}
	return &out, nil
}

// DeleteToken Delete object
func (c Core) DeleteToken(ctx context.Context, id int) (*Token, error) {
	var out Token
	if err := c.store.Token().Delete(ctx, &out, orm.Where("id=?", id)); err != nil {
		return nil, reason.ErrDB.Withf(`Del err[%s]`, err.Error())
	}
	return &out, nil
}
