// Code generated by godddx, DO AVOID EDIT.
package tokenapi

import (
	"strconv"
	"time"

	"github.com/gin-gonic/gin"
	"gorm.io/gorm"

	"github.com/kalandramo/milady/domain/token"
	"github.com/kalandramo/milady/domain/token/store/tokencache"
	"github.com/kalandramo/milady/domain/token/store/tokendb"
	"github.com/kalandramo/milady/pkg/conc"
	"github.com/kalandramo/milady/pkg/orm"
	"github.com/kalandramo/milady/pkg/web"
)

type TokenAPI struct {
	TokenCore token.Core
}

func NewTokenAPI(db *gorm.DB) TokenAPI {
	var store token.Storer
	store = tokendb.NewDB(db).AutoMigrate(orm.GetEnabledAutoMigrate())
	// 如果需要缓存，可以取消注释
	// 目前缓存是通过 id 缓存，而此领域没有获取 id 的条件
	store = tokencache.NewCache(store, conc.NewTTLCache(time.Hour))
	core := token.NewCore(store)
	return TokenAPI{TokenCore: core}
}

func Register(g gin.IRouter, api TokenAPI, handler ...gin.HandlerFunc) {
	{
		group := g.Group("/tokens", handler...)
		group.GET("", web.WrapH(api.listTokens))
		group.DELETE("/:id", web.WrapH(api.deleteToken))
		// group.GET("/:id", web.WrapH(api.getToken))
		// group.PUT("/:id", web.WrapH(api.editToken))
		// group.POST("", web.WrapH(api.addToken))
	}
}

// >>> token >>>>>>>>>>>>>>>>>>>>

func (a TokenAPI) listTokens(c *gin.Context, in *token.FindTokenInput) (any, error) {
	items, total, err := a.TokenCore.ListTokens(c.Request.Context(), in)
	return gin.H{"items": items, "total": total}, err
}

// func (a TokenAPI) getToken(c *gin.Context, _ *struct{}) (any, error) {
// 	tokenID, _ := strconv.Atoi(c.Param("id"))
// 	return a.TokenCore.GetToken(c.Request.Context(), tokenID)
// }

// func (a TokenAPI) editToken(c *gin.Context, in *token.EditTokenInput) (any, error) {
// 	tokenID, _ := strconv.Atoi(c.Param("id"))
// 	return a.TokenCore.EditToken(c.Request.Context(), in, tokenID)
// }

// func (a TokenAPI) addToken(c *gin.Context, in *token.AddTokenInput) (any, error) {
// 	return a.TokenCore.AddToken(c.Request.Context(), in)
// }

func (a TokenAPI) deleteToken(c *gin.Context, _ *struct{}) (any, error) {
	tokenID, _ := strconv.Atoi(c.Param("id"))
	return a.TokenCore.DeleteToken(c.Request.Context(), tokenID)
}
